services:
  gui:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - floci
      - sidecar
    environment:
      - SIDECAR_URL=http://sidecar:8000
    ports:
      - "3000:3000"
