import boto3
import json
from floci_backend.config import config

class IacGenerator:
    def __init__(self):
        self.endpoint_url = config.aws_endpoint_url
        self.region = config.aws_region
        self.access_key = config.aws_access_key_id
        self.secret_key = config.aws_secret_access_key

    def _get_client(self, service_name: str):
        return boto3.client(
            service_name,
            endpoint_url=self.endpoint_url,
            region_name=self.region,
            aws_access_key_id=self.access_key,
            aws_secret_access_key=self.secret_key
        )

    def export_to_terraform(self) -> str:
        s3_client = self._get_client('s3')
        sqs_client = self._get_client('sqs')
        dynamodb_client = self._get_client('dynamodb')
        lambda_client = self._get_client('lambda')
        kms_client = self._get_client('kms')

        terraform_code = [
            'provider "aws" {',
            f'  region = "{self.region}"',
            '}',
            ''
        ]

        # S3
        try:
            buckets = s3_client.list_buckets().get('Buckets', [])
            for bucket in buckets:
                name = bucket['Name']
                terraform_code.extend([
                    f'resource "aws_s3_bucket" "{name.replace("-", "_")}" {{',
                    f'  bucket = "{name}"',
                    '}',
                    ''
                ])
        except Exception:
            pass

        # SQS
        try:
            queues = sqs_client.list_queues().get('QueueUrls', [])
            for q_url in queues:
                q_name = q_url.split('/')[-1]
                terraform_code.extend([
                    f'resource "aws_sqs_queue" "{q_name.replace("-", "_")}" {{',
                    f'  name = "{q_name}"',
                    '}',
                    ''
                ])
        except Exception:
            pass

        # DynamoDB
        try:
            tables = dynamodb_client.list_tables().get('TableNames', [])
            for table in tables:
                table_info = dynamodb_client.describe_table(TableName=table).get('Table', {})
                hash_key = None
                for key_schema in table_info.get('KeySchema', []):
                    if key_schema['KeyType'] == 'HASH':
                        hash_key = key_schema['AttributeName']
                        break

                terraform_code.extend([
                    f'resource "aws_dynamodb_table" "{table.replace("-", "_")}" {{',
                    f'  name = "{table}"',
                    '  billing_mode = "PAY_PER_REQUEST"'
                ])
                if hash_key:
                    terraform_code.extend([
                        f'  hash_key = "{hash_key}"',
                        '  attribute {',
                        f'    name = "{hash_key}"',
                        '    type = "S"',
                        '  }'
                    ])
                terraform_code.extend([
                    '}',
                    ''
                ])
        except Exception:
            pass

        # Lambda
        try:
            functions = lambda_client.list_functions().get('Functions', [])
            for func in functions:
                f_name = func['FunctionName']
                handler = func.get('Handler', 'index.handler')
                runtime = func.get('Runtime', 'python3.9')
                terraform_code.extend([
                    f'resource "aws_lambda_function" "{f_name.replace("-", "_")}" {{',
                    f'  function_name = "{f_name}"',
                    f'  handler = "{handler}"',
                    f'  runtime = "{runtime}"',
                    '  role = "arn:aws:iam::123456789012:role/mock-role"',
                    '}',
                    ''
                ])
        except Exception:
            pass

        # KMS
        try:
            keys = kms_client.list_keys().get('Keys', [])
            for i, key in enumerate(keys):
                terraform_code.extend([
                    f'resource "aws_kms_key" "key_{i}" {{',
                    f'  description = "KMS key {key["KeyId"]}"',
                    '}',
                    ''
                ])
        except Exception:
            pass

        return "\n".join(terraform_code)

    def export_to_cdk(self) -> str:
        raise NotImplementedError("CDK export is not implemented yet.")

    def export_recipes_to_terraform(self, installations: dict, recipes: list[dict]) -> str:
        """Generate Terraform HCL for all RUNNING marketplace recipe installations."""
        recipe_map = {r['id']: r for r in recipes}

        lines = [
            'provider "aws" {',
            f'  region = "{self.region}"',
            '}',
            '',
            '# Generated by Floci Studio — marketplace recipe installations',
            '',
        ]

        generated = 0
        skipped = []

        for recipe_id, inst in installations.items():
            if inst.get('status') != 'RUNNING':
                continue
            recipe = recipe_map.get(recipe_id)
            if not recipe:
                skipped.append(recipe_id)
                continue
            block = self._recipe_terraform_block(recipe_id, inst.get('vars', {}))
            if block:
                lines.extend(block)
                generated += 1
            else:
                aws_service = (recipe.get('aws') or {}).get('service', '(no AWS mapping)')
                skipped.append(f"{recipe_id} → {aws_service}")

        if skipped:
            lines += [
                f'# Skipped {len(skipped)} recipe(s) with no direct Terraform resource:',
            ] + [f'#   {s}' for s in skipped] + ['']

        if generated == 0:
            lines.append('# No running recipes with Terraform mappings found.')

        return '\n'.join(lines)

    def _recipe_terraform_block(self, recipe_id: str, vars: dict) -> list[str] | None:
        name = recipe_id.replace('-', '_')

        if recipe_id == 'postgres':
            return [
                f'resource "aws_db_instance" "{name}" {{',
                '  engine              = "postgres"',
                '  engine_version      = "15"',
                '  instance_class      = "db.t3.micro"',
                f'  db_name             = "{vars.get("POSTGRES_DB", "postgres")}"',
                f'  username            = "{vars.get("POSTGRES_USER", "postgres")}"',
                '  password            = var.postgres_password',
                f'  port                = {vars.get("POSTGRES_PORT", 5432)}',
                '  allocated_storage   = 20',
                '  skip_final_snapshot = true',
                '}', '',
                'variable "postgres_password" {',
                '  description = "PostgreSQL master password"',
                '  sensitive   = true',
                '}', '',
            ]

        if recipe_id == 'mysql':
            return [
                f'resource "aws_db_instance" "{name}" {{',
                '  engine              = "mysql"',
                '  engine_version      = "8.0"',
                '  instance_class      = "db.t3.micro"',
                f'  db_name             = "{vars.get("MYSQL_DATABASE", "mydb")}"',
                f'  username            = "{vars.get("MYSQL_USER", "mysql")}"',
                '  password            = var.mysql_password',
                f'  port                = {vars.get("MYSQL_PORT", 3306)}',
                '  allocated_storage   = 20',
                '  skip_final_snapshot = true',
                '}', '',
                'variable "mysql_password" {',
                '  description = "MySQL master password"',
                '  sensitive   = true',
                '}', '',
            ]

        if recipe_id == 'redis':
            return [
                f'resource "aws_elasticache_replication_group" "{name}" {{',
                '  replication_group_id = "floci-redis"',
                '  description          = "Floci Redis"',
                '  node_type            = "cache.t3.micro"',
                '  num_cache_clusters   = 1',
                f'  port                 = {vars.get("REDIS_PORT", 6379)}',
                '  transit_encryption_enabled = true',
                '  auth_token           = var.redis_auth_token',
                '}', '',
                'variable "redis_auth_token" {',
                '  description = "Redis AUTH token (--requirepass)"',
                '  sensitive   = true',
                '}', '',
            ]

        if recipe_id == 'mongodb':
            return [
                f'resource "aws_docdb_cluster" "{name}" {{',
                '  cluster_identifier  = "floci-docdb"',
                f'  master_username     = "{vars.get("MONGO_INITDB_ROOT_USERNAME", "root")}"',
                '  master_password     = var.mongo_password',
                '  skip_final_snapshot = true',
                '}', '',
                f'resource "aws_docdb_cluster_instance" "{name}_instance" {{',
                '  identifier         = "floci-docdb-0"',
                f'  cluster_identifier = aws_docdb_cluster.{name}.id',
                '  instance_class     = "db.t3.medium"',
                '}', '',
                'variable "mongo_password" {',
                '  description = "DocumentDB master password"',
                '  sensitive   = true',
                '}', '',
            ]

        if recipe_id == 'rabbitmq':
            return [
                f'resource "aws_mq_broker" "{name}" {{',
                '  broker_name        = "floci-rabbitmq"',
                '  engine_type        = "RabbitMQ"',
                '  engine_version     = "3.13"',
                '  host_instance_type = "mq.t3.micro"',
                '  deployment_mode    = "SINGLE_INSTANCE"',
                '  user {',
                f'    username = "{vars.get("RABBITMQ_DEFAULT_USER", "guest")}"',
                '    password = var.rabbitmq_password',
                '  }',
                '}', '',
                'variable "rabbitmq_password" {',
                '  description = "RabbitMQ admin password"',
                '  sensitive   = true',
                '}', '',
            ]

        if recipe_id in ('kafka', 'redpanda'):
            return [
                f'resource "aws_msk_cluster" "{name}" {{',
                '  cluster_name           = "floci-kafka"',
                '  kafka_version          = "3.6.0"',
                '  number_of_broker_nodes = 3',
                '  broker_node_group_info {',
                '    instance_type  = "kafka.t3.small"',
                '    client_subnets = [/* add subnet IDs */]',
                '    storage_info {',
                '      ebs_storage_info { volume_size = 100 }',
                '    }',
                '  }',
                '}', '',
            ]

        if recipe_id in ('elasticsearch', 'weaviate', 'qdrant', 'meilisearch'):
            domain = recipe_id.replace('_', '-')
            return [
                f'resource "aws_opensearch_domain" "{name}" {{',
                f'  domain_name    = "floci-{domain}"',
                '  engine_version = "OpenSearch_2.11"',
                '  cluster_config {',
                '    instance_type = "t3.small.search"',
                '  }',
                '  ebs_options {',
                '    ebs_enabled = true',
                '    volume_size = 20',
                '  }',
                '}', '',
            ]

        if recipe_id == 'clickhouse':
            return [
                f'resource "aws_redshift_cluster" "{name}" {{',
                '  cluster_identifier  = "floci-redshift"',
                '  node_type           = "dc2.large"',
                '  number_of_nodes     = 1',
                f'  database_name       = "{vars.get("CLICKHOUSE_DB", "analytics")}"',
                f'  master_username     = "{vars.get("CLICKHOUSE_USER", "default")}"',
                '  master_password     = var.clickhouse_password',
                '  skip_final_snapshot = true',
                '}', '',
                'variable "clickhouse_password" {',
                '  description = "Redshift master password"',
                '  sensitive   = true',
                '}', '',
            ]

        if recipe_id == 'keycloak':
            return [
                f'resource "aws_cognito_user_pool" "{name}" {{',
                '  name = "floci-user-pool"',
                '  password_policy {',
                '    minimum_length    = 8',
                '    require_lowercase = true',
                '    require_numbers   = true',
                '  }',
                '}', '',
                f'resource "aws_cognito_user_pool_client" "{name}_client" {{',
                '  name         = "floci-app-client"',
                f'  user_pool_id = aws_cognito_user_pool.{name}.id',
                '}', '',
            ]

        if recipe_id == 'vault':
            return [
                f'resource "aws_secretsmanager_secret" "{name}" {{',
                '  name                    = "floci/vault"',
                '  description             = "Migrated from local HashiCorp Vault dev instance"',
                '  recovery_window_in_days = 0',
                '}', '',
            ]

        if recipe_id == 'airflow':
            return [
                f'resource "aws_mwaa_environment" "{name}" {{',
                '  name               = "floci-airflow"',
                '  airflow_version    = "2.9.2"',
                '  execution_role_arn = aws_iam_role.mwaa_role.arn',
                '  source_bucket_arn  = aws_s3_bucket.mwaa_dags.arn',
                '  dag_s3_path        = "dags/"',
                '  network_configuration {',
                '    security_group_ids = [/* add sg IDs */]',
                '    subnet_ids         = [/* add private subnet IDs */]',
                '  }',
                '}', '',
                'resource "aws_s3_bucket" "mwaa_dags" {',
                '  bucket = "floci-mwaa-dags"',
                '}', '',
            ]

        if recipe_id == 'nats':
            return [
                '# NATS JetStream → Amazon SQS + SNS for pub/sub patterns',
                f'resource "aws_sqs_queue" "{name}" {{',
                '  name                       = "floci-nats-queue"',
                '  visibility_timeout_seconds = 30',
                '}', '',
            ]

        if recipe_id == 'supabase':
            return [
                '# Supabase → Amazon RDS (PostgreSQL) + Amazon Cognito',
                f'resource "aws_db_instance" "{name}_db" {{',
                '  engine              = "postgres"',
                '  engine_version      = "15"',
                '  instance_class      = "db.t3.micro"',
                '  db_name             = "postgres"',
                '  username            = "postgres"',
                '  password            = var.supabase_db_password',
                '  allocated_storage   = 20',
                '  skip_final_snapshot = true',
                '}', '',
                f'resource "aws_cognito_user_pool" "{name}_auth" {{',
                '  name = "floci-supabase-auth"',
                '}', '',
                'variable "supabase_db_password" {',
                '  description = "Supabase (RDS) database password"',
                '  sensitive   = true',
                '}', '',
            ]

        if recipe_id == 'temporal':
            return [
                '# Temporal → AWS Step Functions (serverless) or ECS (self-hosted)',
                f'resource "aws_sfn_state_machine" "{name}" {{',
                '  name     = "floci-temporal-workflow"',
                '  role_arn = aws_iam_role.sfn_role.arn',
                '  type     = "STANDARD"',
                '  definition = jsonencode({',
                '    Comment = "Migrated from local Temporal"',
                '    StartAt = "FirstState"',
                '    States  = { FirstState = { Type = "Pass", End = true } }',
                '  })',
                '}', '',
            ]

        if recipe_id in ('iotcore', 'aws-iot-core'):
            return [
                f'resource "aws_iot_thing" "{name}_device" {{',
                '  name = "floci-iot-device"',
                '}', '',
                f'resource "aws_iot_topic_rule" "{name}_rule" {{',
                '  name        = "floci_iot_rule"',
                '  enabled     = true',
                '  sql         = "SELECT * FROM \'#\'"',
                '  sql_version = "2016-03-23"',
                '  sqs {',
                '    queue_url  = aws_sqs_queue.iot_queue.url',
                '    role_arn   = aws_iam_role.iot_role.arn',
                '    use_base64 = false',
                '  }',
                '}', '',
            ]

        if recipe_id == 'transfer':
            return [
                f'resource "aws_transfer_server" "{name}" {{',
                '  protocols              = ["SFTP"]',
                '  identity_provider_type = "SERVICE_MANAGED"',
                '  endpoint_type          = "PUBLIC"',
                '}', '',
            ]

        if recipe_id == 'minio':
            return [
                '# MinIO → Amazon S3. Your S3 buckets are exported by the core IaC tool.',
                '# Run export_to_terraform() to include them.', '',
            ]

        return None
