services:
  mailpit:
    image: axllent/mailpit:latest
    container_name: floci-mailpit
    ports:
      - "${MAILPIT_SMTP_PORT:-1025}:1025" # Puerto SMTP
      - "${MAILPIT_WEB_PORT:-8025}:8025" # Puerto de la interfaz web
    environment:
      MP_MAX_MESSAGES: 500
    restart: unless-stopped
