services:
  pocketbase:
    image: muchobien/pocketbase:latest
    container_name: floci-pocketbase
    ports:
      - "${POCKETBASE_PORT:-8090}:8090" # API y Panel de control
    volumes:
      - ./pb_data:/pb_public/pb_data
    restart: unless-stopped
